let prod;
prod='<table border="1"><caption>Конструкция switch</caption>'
+'<td id="lev">'
+'<li><a>Синтаксис</a> <i>(имеет один или более блок(ов) case и необязательный '
+'парметр default)</i><br>'
+'switch(x){<br>'
	+'case "value1": //=if(x==="value")<br>'
		+'...<br>'
	+'   [break]<br>'
+'	case "value2": //=if(x==="value2")<br>'
		+'...<br>'
	  +' [break]<br>'
	+'default:<br>'
  +'      ...<br>'
+'[break]}	<br>'
+'<ul>'
+'<li type="disc">Переменная x проверяется на строгое равенство первому значению '
+'value1, затем второму value2 и так далее.</li>'
+'<li type="disc">Если соответствие установлено - switch начинает выполняться от '
+'соотвествующей директивы case и далее, до ближайшего break(или до конца switch).</li>'
+'<li type="disc">Ни один case не совпал - выполняется default(если указан).</li>'
+'</ul></li><li>'
+'<a>Пример работы</a><br>'
+'let a=2+2;<br>'
+'switch(a){<br>'
  +' case 3:<br>'
+'alert("malo"); break;<br>'
  +' case 4:<br>'
+'alert("verno"); break;<br>'
  +' case 5:<br>'
+'alert("mnogo"); break;<br>'
  +' default:<br>'
+'alert("bred");}   <i>//verno</i><br>'
+'</li><li><a>Без break</a><br>'
+'let a=2+2;<br>'
+'switch(a){<br>'
	+'case 3: alert("malo");<br>'
	+'case 4: alert("verno");<br>'
	+'case 5: alert("mnogo");<br>'
	+'default: alert("bred");<br>'
+'} <i>//verno mnogo bred</i><br>'
+'<i>Забавный момент:</i><br>'
+'let a="1"; <i>//!</i><br>'
+'let b=0;<br>'
+'switch(+a){<br>'
	+'case b+1:<br>'
	+'alert("proydet, +a=1 ");<br>' 
+'	break;<br>'
	+'default:<br>'
+'alert("net");} <i>//proydet, +a=1</i><br>'
+'</li><li><a>Меж прочим, case можно группировать</a><br>'
+'let a=3;<br>'
+'switch(a){<br>'
	+'&ensp;case 4:<br>'
+'	   &ensp;&ensp;alert("Verno!");<br>'
	  +' break;<br>'
	+'&ensp;&ensp;case 3: <i>//группируем case</i><br>'
+'&ensp;	case 5:<br>'
	+'   alert("neverno!");<br>'
+'	   alert("vali na mathematik!");<br>'
	  +' break;<br>'
	+'default: alert("stranno!");<br>'
+'}	<i>//neverno vali na mathematik</i><br>'
+'</li>'
	+'<ol><h5>Задачи</h5>'
+'<li><a>Напишите if, аналогичный switch</a><br>'
+'let a=prompt("browser","");<br>'
+'if(a=="Edge") {alert("this is Edje");}<br>'
+'else if(a=="Chrome"||a=="Firevox"||a=="Safari"||a=="Opera") {alert("poydot");}<br>'
+'else {alert("ne v kurse");} <i>//всё верно выдаёт</i><br></li><li>'
+'<a>Переписываем if на switch</a><br>'
+'const number=+prompt("givo number 0-3","");<br>'
+'switch(number){<br>'
 +'  case 0:alert ("null"); break;<br>'
  +' case 1:alert ("odin"); break;<br>'
+'   case 2:alert ("dva"); break;<br>'
  +' default: alert("no");<br>'
+'} <i>//всё верно выдаёт</i><br>'
+'else {alert("ne v kurse");} <i>//всё верно выдаёт</i><br>'
+'</li></ol>'
+'<ol><h4>Функции</h4>'
+'<a>Примеры встроенных функций: alert(message),prompt(massage,default),'
+' confirm(question) </a><i> или, как обычно, свои объявить</i><br>'
+'<li><a>Объявление функции</a><br>'
+'typa: <br>function showMessage(){<br>'
+'alert("Privet agentura");<br>}'
+'showMessage(); <i>//Privet agentura</i></li><li>'
+'<a>Локальные переменные</a><br>'
+'function showM(){<br>'
	+'let mes="Privet, I JS!"; <i>//переменная локальная</i><br>'
+'alert(mes);}<br>'
+'showM(); <i>//Privet, I JS!</i><br>'
+'alert(mes); <i>//вообще ничего не загрузил</i><br></li><li>'
+'<a>Внешние переменные</a><br>'
+'let userName="Goga";<br>'
+'function showM(){<br>'
	+'let mes="Hello, "+ userName;<br>'
+'alert(mes);}<br>'
+'showM(); <i>//Hello, Goga</i><br>'
+'<a>Ещё:</a><br>'
+'let userN="Goga";<br>'
+'function showM(){<br>'
	+'userN="Vazgen"; <i>//pomenjali</i><br>'
	+'let mes="privet, "+userN;<br>'
+'alert(mes);}<br>'
+'alert(userN); <i>//Goga (pered vizovom)</i><br>'
+'showM(); <i>//Privet, Vasgen</i><br>'
+'alert(userN); <i>//Vasgen (очень странная коснтрукция)</i><br>'
+'<i>в коде ниже показана работа использования <br>функцией уже локальной переменной</i><br>'
+'let userN="Vazgen";<br>'
+'function showM(){<br>'
	+'let userN="Goga"; <i>//vnutri</i><br>'
	+'let mes="Privet, "+userN;<br>'
	+'alert(mes);<br>'
+'} showM(); <i>//Privet, Goga</i><br>'
+'alert(userN); <i>//Vazgen (snarugi)</i><br>'
+'<a>глобальные переменные видны из любой функции</a><br></li><li>'
+'<a>Параметры</a><br>'
+'<i>Выглядит это примерно так:</i><br>'
+'function showM(form,text){ <i>//param from,text</i><br>'
+'alert(form+": "+text);}<br>'
+'showM("Anna", "Privet!"); <i>//Anna: Privet!</i><br>'
+'showM("Anna","v porjadke?"); <i>//Anna: v porjadke?</i><br></li><li>'
+'<i>Покажем, как функция извне изменяет значение from</i><br>'
+'function showM(from,text){<br>'
	+'from="*"+from+"*"; <i>//украшение</i><br>'
	+'alert(from+": "+text);}<br>'
+'let from="Anna";<br>'
+'showM(from, "Hello"); <i>//*Anna*: Hello - !украшение есть</i><br>'
+'alert(from); <i>//Anna(логично, даже спорить не буду)</i><br>'
+'<img src="https://i.postimg.cc/Vs93TFHk/aip.png" width="380" hight="240"/>'
+'<ul><li type="disc">Параметр - переменная,указанная при объявлении</li>'
+'<li type="disc">Аргумент - значение, которое передаётся при вызове</li></ul></li><li>'
+'<a>Значение по умолчанию</a><br> showM("Anna"); <i>типа пример</i><br>'
+'<i>Но зададим полностью:</i><br>'
+'function showM(from,text="ничего не пишем"){<br>'
	+'alert(from+": "+text);<br>'
+'} showM("Anna"); <i>//Anna: ничего не пишем(смешно)</i><br></li><li>'
+'<a>Явная проверка не undefined</a><br>'
+'function showM(from,text){<br>'
+'	if(text===undefined){<br>'
		+'text="text no";}<br>'
	+'alert(from+": "+text);}<br>'
+'showM(); <i>//undefined: text no (как интересно)</i><br>'
+'function showM(from,text){<br>'
	+'<i>//...bla,bla</i><br>'
	+'text=text||"text no";<br>'
	+'alert(text);<br>'
+'} showM(); <i>//text no</i><br></li><li>'
+'<a>Альтернативные парметры по умолчанию<img '
+'src="https://i.postimg.cc/FdK47BVL/image.png" width="340"/></a><br>'
+'<i>Присваиваем значение потом:</i><br>'
+'function showM(text){<br>'
+'	if(text===undefined){ <i>//если параметра нет</i><br>'
	  +'text="no text";<br>'
	+'}alert(text);<br>'
+'}showM(); <i>//no text(ну, так и должно быть)</i><br>'
+'</li></ol>'
+'<ul><h4>Возврат значения</h4><li><i>Простейший пример:</i><br>'
+'function sum(a,b){<br>'
   +'return a+b;}<br>'
  +' let result=sum(12,23);<br>'
+'   alert(result); <i>//35</i><br>'
+'<a>вызовов return может быть больше одного<br><center>(покажем это)</center></a><nobr>'
+'function checkA(age){<br>'
+'	if(age>=18){<br>'
	+'(1)	return true;<br>'
+'	}else{<br>'
	+'(2)	return confirm("rodaki znajut?");<br>'
+'}}<br>'
+'let age=prompt("skoka let?",18);<br>'
+'if(checkA(age)){<br>'
	+'alert("dostup");<br>'
+'	}else{<br>'
	+'	alert("idi, klop");<br>'
+'		}<i>//программа пропустит в любом случае, если скажешь,<br> что предки знают</i><br>'
+'<i>return без значения - моментальный выход из функции</i><br>'
+'function showM(age){<br>'
	+'if(!checkA(age)){<br>'
	+'return;}else{<br>'
+'alert("Вы смотрите телевизор");<br>'
+'}} <i>//ничего не загрузилось</i><br></li><li>'
+'<a>Обязательно надо показать как работает<br>'
+'оператор нулевого слияния</a><br>'
+'function showC(count){<br>'
	+'<i>//null || undefined -> неизвестно</i><br>'
	+'alert(count ?? "Неизвестно");<br>'
+'}<br>'
+'showC(0); <i>//0</i><br>'
+'showC(null); <i>//Неизвестно</i><br>'
+'showC(); <i>//Неизвестно (всё правильно)</i><br></li><li>'
+'<a>Возврат значения</a><br>'
+'результат возвращается к источнику и используется там<br>'
+'function sum(a,b){<br>'
	+'return a+b;<br>'
+'} let result=sum(8,9);<br>'
+'alert(result); <i>//17</i><br></li>'
+'<li><a>Итог</a><ul>'
+'объявление функции имеет вид:<br>'
+'function имя(параметры,через,запятую){<br>'
+'&ensp;/*тело,код функции*/<br>}<br>'
+'<li type="square">Функции имеют доступ к внешним параметрам изнутри наружу</li>'
+'<li type="square">значения копируются в значения и становятся локальными</li>'
+'<li type="square">функция возвращает значение, иначе undefined</li>'
+'<i>есть следующие принципы имён функций</i><br>'
+'<li type="square">Имя функции чётко и понятно отображает её суть</li>'
+'<li type="square">Так как обычно это действие, то название часто является глаголом</li>'
+'<li type="square">Общепринятые префиксы: create.., show.., get.., check</li>'
+'</ul></li><hr><h5>заслушаем клоунов</h5>'
+'<br>?. let age=prompt("skoka let? ","");<br>'
  +' function checkA(age){<br>'
	+'   return(age>18)?true:confirm("Predki znajut? ");<br>'
   +'} checkA(age); <i>//работает</i><br>'
+'||.<i> - не идёт</i></li><li> '
+'<a>Поговорим об операторе continue</a><br>'
+'<i>прерывает выполнение на метке и функция продолжает работу<br> на следующей '
+'итерации</i><br><ul><i>поподробнее:</i><br>'
+'<li type="square">В цикле while оно переносит воток выполнения к условию</li>'
+'<li type="square">В цикле for оно переносит поток выполнения к финальному<br> выражению'
+' в описании цикла</li>'
+'</ul></li><ol><b>Примеры</b><br><li>'
+'<i>continue с циклом while</i><br>'
+'i=0;<br>'
+'n=0;<br>'
+'m=0;<br>'
+'while(i<5){<br>'
	+'i++;<br>'
	+'m+=i;<br>'
	+'if(i===3){<br>'
		+'continue;}<br>'
	+'n+=i;<br>'
+'}prompt("с тройкой",m); <i>//15</i><br>'
+'prompt("без тройки",n); <i>//12</i><br>'
+'<i>Вот парикольная. Использование continue вместе с меткой:</i><br>'
+'var i=0,j=0;<br>'
+'checkI:while(i<4){<br>'
+'	alert("i: "+i);<br>'
	+'i+=1;<br>'
  +' checkJ:while(j>4){<br>'
+'alert("j: "+j);<br>'
+'j-=1;<br>'
+'if(j%2==0)continue checkJ;<br>'
+'alert(j+"нечётное. ");<br>'
  +' }<br>'
+'alert("i= "+i );<br>'
+'alert("j= "+j );<br>'
+'}/*i: 0;i= 1;j= 0;<br>'
+'i: 1;i= 2;j= 0;<br>'
+'i: 2;i= 3;j= 0;<br>'
+'i= 3;i= 4;j= 0 <i>(именно так и никак иначе) а checkJ не нашёл</i>*/<br></li><li>'
+'<a>Пустая инструкция<br><href="https://postimg.cc/ThxwBZT1"><img src="https://i.postimg.cc/ThxwBZT1/pijs.png"></a><br>'
+'var arr=[1,2,3];<br>'
+'<i>//приравняем все значения массива к нулю</i><br>'
+'for(i=0; i&lt;arr.length; arr[i++]=0 <i>/*выражения*/</i>);<br>' 
+'alert(arr); <i>//0 0 0 (вот жмот)</i> <br>'

+'</li></ol>'
+'</ul>'
+'</td><td id="prav">'
  +'<a>А это наша правая колонка</a><br>'
    +'<ul><h4>export</h4> ставим:<br>'  
+'<li>перед объявлением переменных, функций и классов</li>'
+'<li>отдельно, при этом в фигурных скобках указывается, что именно экспортируется</li>'
+'</ul>'
+'<ol><h4>Функции</h4><i>(продолжаем)</i><br>'
+'<li>Function Expression<br>'
+'<i>объявление:</i><br>'
+'let sayHi=function(){<br>'
  +' alert("good");<br>'
+'   }; sayHi();<i>//good</i><br>'
+'<i>Тут переменная sayHi() полчает значение от function(){alert("text");}</i><br>'
+'<a>Так как функция является занчением, то:</a><br>'
+'function sayHi(){<br>'
	+'alert("Balbes");<br>'
+'} alert(sayHi); <i>//тут был произведён вывод кода</i><br>'
+'<i>(!) в js c функцией можно работать как со значением</i><br>'
+'function sayH(){ <i>//(1) создаём</i><br>'
  +' alert("Nonsens");}<br>'
+'let func=sayH; <i>//(2) копируем</i><br>'
+'func(); <i>//(3) Nonsens(это копия)</i><br>'
+'sayH(); <i>// Nonsens тоже (оригинал)</i><br>'
+'<ol><i>Ща, тут всё подробно разберём</i><br>'
+'<li>Function Declsration (1) создаёт функцию и помещает её в sayH</li>'
+'<li>В строке (2) её значение копируется в переменную func. Обращаем '
+'внимание, что скобок после sayH нет. Иначе бы в func был записан '
+'результат вызова sayH(), а не саму функцию</li>'
+'<li>О, чудо фнкции sayH() и func() идентичны</li></ol>'
+'<i>для объявления её тоже можно использовать:</i><br>'
+'let sayH=function(){ <i>//typa sozdali</i><br>'
+'alert("zdorovo");}<br>'
  +' let func=sayH;<br>'
+'   func(); <i>// zdorovo</i><br>'
+'<i>не забываем также, что в случае с Function Declaration ставится '
+'ставится точка с запятой(нужно для простоты кода)</i><br></li>'
+'<li><a>Функции - "колбэки"</a><br>'
+'Делаем так: пишем ask(question,yes,no), где<br>'
+'<a>question </a>- Текст вороса<br>'
+'<a>yes </a> - функция при ответе yes<br>'
+'<a>no</a> - функция при ответе no<br>'
+'<i>поехали: </i><br>'
+'function ask(question,yes,no){<br>'
	+'if(confirm(question))yes()<br>'
	+'	else no();}<br>'
+'function showO(){alert("ladno");}<br>'
+'function showC(){alert("otkaz");}<br>'
+'<i>//теперь функции showO и showC передаются в качетве аргумента</i><br>'
+'ask("otoydi",showO,showC); <i>//да, вопрос и два ответа</i><br>'
+'<a>аргументы showO и showC функции ask называются функциями-колбэками</a><br>'
+'<i>Можно и проще:</i><br>'
+'function ask(quest,yes,no){<br>'
	+'if(confirm(quest))yes()<br>'
+'else no();}<br>'
+'ask("Ты трезвый?",<br>'
    +'function(){alert("prohodi")},<br>'
	+'function(){alert("ne-a")}<br>'
+'	); <i>//реакция правильная</i><br></li><li>'
+'<h5>Учимся oтличать Function Declaration от Function Expression</h5><br>'
+'<ul><li type="disc"><i>Function Declaration</i><br>'
+'function sum(a,b){<br>'
+'&ensp;return a+b;}'
+'</li><li type="disc"><i>Function Expression</i><br>'
+'let sum=function(a,b){<br>'
+'&ensp;return a+b;<br>'
+'}; <i>//после всего выражения ставится ещё одна ;</i><br>'
+'</li></ul>'
+'Ещё важное отличие: <b>Function Expression создётся, когда выполнение доходит '
+'до него и затем уже может использоваться</b><br>'
+'<i>C Functioln Declaration всё обстоит иначе</i><br>'
+'<b>Function Declaration может(!) быть вызвана раньше, чем она объявлена</b><br>'
+'sayHi("Diana"); //Privet, Diana <i>уже вызвана</i><br>'
+'function sayHi(name){<br>'
	+'alert(`Privet, ${name}`);<br>'
+'} <i>//тут ничего нет</i><br>'
+'C Function Expression такой код вызвал бы ошибку<br>'
+'<a>Ещё маленькое дополнение: в строгом режиме, когда Function Declaration '
+'нахзодится в блоке {...}, функция доступна везде внутри блока, но не снаружи его.</a><br>'
+'<i>вот пример: </i><br>'
+'let age=prompt("skoka let? ",""); <i>//primer</i><br>'
+'if(age<18){<br>'
+'	welcome();           <i>  // \ (выполнится)</i><br>'
	+'function welcome(){  <i>//  |</i><br>'
+'	alert("Privet ");}     <i>//  |</i><br>'
	+'	welcome();         <i>// / (тоже сработает)</i><br>'
+'}else{<br>'
	+'function welcome(){<br>'
	+'	alert("Zdorovo")<br>'
+'}} <i>//скобочка закрывается и...</i><br>'
+'welcome(); <i>//Если менее 18, то три "привета" зараз</i><br>'
+'<i>Делаем так, чтобы функция была видна снаружи if. <a>Смотрим:</a></i><br>'
+'<a href="https://postimg.cc/MvzJwtmT">'
+'<img src="https://i.postimg.cc/MvzJwtmT/image.jpg" width="300" hight="20000"></a>'
+'let kol=prompt("Skoka tebe piva? ",18);<br>'
+'let welcome;<br>'
+'if(kol<18){<br>'
  +' welcome=function(){<br>'
    +'   alert("Malo!");<br>'
   +'}; <i>//!</i><br>'
   +'}else{<br>'
+'welcome=function(){<br>'
  +' alert("Bery!");<br>'
   +'};}<br>'
+'welcome(); <i>// да, всё верно показывает</i><br>'
+'<i>Ещё проще сделаем. Используем оператор ?:</i><br>'
+'let kol=prompt("Skoka piva?",18);<br>'
+'let welcome=(kol<18)?<br>'
   +'function(){alert("Malovato!");}:<br>'
  +' function(){alert("Pouydet");};<br>'
+'welcome(); <i>//работает</i>   <br>'
+'</li><ul><a>Забабахаем итог:</a>'
+'<li type="disc">Функции - это значения. Они могут быть присвоены, '
+'скопированы или объявлены в любом месте кода.</li>'
+'<li type="disc">Если функция объявлена как отдельная инструкция в основном '
+'потоке кода, то это "Function Declaration".</li>'
+'<li type="disc">Если функция была создана как часть выражения, то это '
+'"Function Expression0".</li>'
+'<li type="disc">Function Declaration обрабатываются перед выполнением '
+'блока кода. Они видны во всём блоке.</li>'
+'<li type="disc">Функции, объявленные при помощи Function Expression '
+'создаются только когда поток выполнения достишгает их.</li>'
+'</ul>'
+'<i>И последнее: </i><a>Function Declafation предпочтительнее</a><br>'
+'<a><img src="https://i.postimg.cc/4H7DLF64/func.jpg"><br>Наслаждаемся</a>'
+'<br><i href="https://postimages.org"><img src="https://i.postimg.cc/52Yd8RxN/gdn.jpg"><br>Ещё картинку вставим:</i>'
+'<li><a>do...while - цикл</a><br>'
+'<i>имеет вид: </i><br>'
+'do{<br>&ensp;выражения<br>}while(условия);<br>'
+'<i>маленький примерчик, где цикл выполняется пока i меньше 5(включая 5)</i><br>'
+'let i=0;<br>'
+'do{<br>'
	+'&ensp;i+=1;<br>'
	+'&ensp;alert(i);<br>'
+'}while(i<5); <i>//немного не так работает, но какая разница</i><br></li><li>'
+'<a>while - самостоятельный цикл:</a><br>'
+'while(условие)<br>&ensp;{выражения}<br><i>для одного выражения скобки обычно '
+'не ставят</i><br>'
+'Пример: <i>цикл работает, пока n меньше трёх</i><br>'
+'var n=0;<br>'
+'var x=0;<br>'
+'while(n<3){<br>'
+'n++;<br>'
+'x+=n;<br>'
+'alert(x);} <i>//1,3,6 (неожиданно. Но после третьего прохода цикл становится '
+'ложным и больше не выполняется)</i><br>'
+'<b>Да, избегайте бесконечных циклов, которые никогда не заканчиваются, когда '
+'Условие никогда не становится ложным</b><br>'
+'while(true){<br>alert("Hello World!");<br>} <i>// что-то подобное</i><br></li><li>'
+'<a>Метка</a><i>если надо, то надо рассмотреть отдельно</i><br>'
+'<i>Метки используются вместе с операторами break и continue</i><br>'
+'<a href="https://postimg.cc/JDvmqQPb"><img src="https://i.postimg.cc/JDvmqQPb/cjs.png" style="width:75%">'
+'</a><br><i>метка цикла JS</i><br>'
+'let str="";<br>'
+'loop1:for(let i=0;i<5;i++){<br>'
  +' if(i===1){<br>'
    +'  continue loop1;<br>'
   +'}<br>'
  +' str=str+i;   }<br>'
+'alert(str); <i>//0234 (сплошняком,без пробелов)</i><br></li>'
+'</ol><ul><a>Несколько примеров</a><br><li type="disc">'
+'<i style="text-decoration:underline">Метка в цикле с оператором continue</i><br>'
+'let i,j;<br>'
+'loop1:for(i=0;i<3;i++){ <i>//1 цикл с меткой "loop1"</i><br>'
  +' loop2:for(j=0;j<3;j++){ <i>//2 цикл с меткой "loop2"</i><br>'
+'      if(i===1&&j===1){<br>'
		+'  continue loop1;<br>'
	  +'}<br>'
	+'  alert("i= "+i+" j= "+j);<br>'
+'}} <i>//0,0; 0,1; 0,2; 1,0; 2,0; 2,1; 2,2</i><br></li><li type="disc">'
+'<i>ещё пример(тоже с continue):</i><br>'
+'let itemsPassed=0;<br>'
+'let i,j;<br>'
+'top:for(i=0;i<items.length;i++){<br>'
+'&ensp;	for(j=0;j<tests.length;j++){<br>'
		+'&ensp;&ensp;if(!tests[j].pass(items[i])){<br>'
	+'		&ensp;&ensp;continue top;<br>'
+'}}itemsPassed++;}<br>'
+'<i>//зачем он нужен, я не понял</i><br></li><li>'
+'<i>исользуем метку с оператором break в цикле</i><br>'
+'let i,j;<br>'
+'loop1: for(i=0;i<3;i++){ <i>//1 цикл</i><br>'
+'   loop2:for(j=0;j<3;j++){ <i>//2 цикл</i><br>'
      +'if(i===1&&j===1){<br>'
	+'  break loop1;}<br>'
  +' alert("i= "+i +"j= "+j);<br>'
+'}} <i>//0-0;0-1;0-2;1-0 (и всё)</i><br>'
+'<i>другой тест: тоже с break</i><br>'
+'let allPass=true;<br>'
+'let i,j;<br>'
+'top:for(i=0;i<items.length;i++){<br>'
	+'for(j=0;j<tests.length;j++){<br>'
+'		if(!tests[j].pass(items[i])){<br>'
		+'	allPass=false;<br>'
	+'		break top;<br>'
+'}}} <i>//где использовать, тоже не понял</i><br>'
+'<a>ещё: блокировка break;</a><br>'
+'foo:{<br>'
	+'&ensp;alert("Priva");<br>'
	+'&ensp;break foo;<br>'
	+'&ensp;alert("this is NO"); <i>ne budet</i><br>'
+'} alert("nu, budem");<br>'
+'<i>//Priva nu, budem, второго нет</i><br></li><li>'
+'<a>Оператор break</a> <i>используется для прерывания цикла</i><br>'
+'<ul><li type="disc">Когдаа используете break без метки, то он прерывает циклы: while, '
+'do...while, for. Или сразу переключает управление к следующей инструкции. '
+'</li><li type="disc">когда используется break с меткой прерывает отмеченное выражение'
+'</li>Синтаксис(примерный): 1. break; 2. break Метка;</ul></li><li>'
+'Пример 1 посмотрим:<br>'
+'for(i=0;i<a.length;i++){<br>'
	+'if(a[i]==theValue){<br>'
	+'	break;<br>'
+'	}} <i>//проходит по всем элементам, пока не надёт нужный</i><br>'
+'Пример 2, <i>удивляемся: </i><br>'
+'let sum=0;<br>'
+'while(true){<br>'
   +'&ensp;let value=+prompt("number: ","");<br>'
   +'&ensp;if(!value) break; <i>//(*)</i><br>'
  +'&ensp; sum+=value;<br>'
+'}alert("Summ: " + sum); <i>//1,2,3,a - 6</i><br>'
+'<i>Ещё пример прерывания метки:</i><br>'
+'var x=0;<br>'
+'var z=0;<br>'
+'labelCancelLoops:while(true){<br>'
	+'alert("Внешний цикл: "+x);<br>'
+'	x+=1;<br>'
	+'z=1;<br>'
+'	while(true){<br>'
		+'alert("Внутренний цикл: "+z);<br>'
	+'	z+=1;<br>'
+'		if(z===10&&x===10){<br>'
			+'break labelCancelLoops;<br>'
		+'}else if(z===10){<br>'
	+'		break;<br>'
+'}}} <i>//оба счётчики от 1 до 10 включительно(считают)</i><br>'
+'</li></ul>'		
+'</td></table>'

let ifel;
ifel='<table><h3>Красочно разукрасим</h3>'
+'<td id="levcool">'
+'<li><i>if else</i><br>'
+'<b>Присваивание в условном выражении</b><br>'
+'if ( x=y ) { /*инструкции*/ } <i>лучше не использовать</i><br>'
+'if (( x=y )) { /*функция*/ } <i>этот способ пойдёт</i></li>'
+'<li><a>import (инструкция)</a><br>'
+'<i>импорт ссылок на значения, которые экспортируются из '
+'внешнего модуля. Все модули находятся в строгом режиме</i><br>'
+'Для работы иструкции пропишите: script type="module"</li><ol>'
+'<a  style="color:maroon">Работаем с модулями</a><br>'
+'<a href="https://postimg.cc/JsxLbFy8"><img src="https://i.postimg.cc/JsxLbFy8/modjs.png" '
+'width="300" hight="250"<br>'
+'<li><a>Импорт всего содержимого модуля</a><br>'
+'import * as myModule from "/modules/my-module.js"; <br>'
+'<i>импорт осуществляется с помощью имени модуля</i></li>'
+'<li><a>Импорт единичного значения модуля</a> <i>(выборочное)</i><br>'
+'import { myExport } from "/modules/my-Module.js"</li>'
+'<li><a>Несколько единичных значений</a><br>'
+'import { foo, bar } from "/modules/my-module.js"; <i>'
+'два параметра вставляются в текущую область видимости</i></li>'
+'<li><a>Импорт значений с более подохящими именами</a><i>'
+'значения можно переименовывать. Вставим shortName и сделаем видимым</i><br>'
+'import { reallyReallyLongModuleExportname as shortName } from "'
+'/modules/my-module.js"</li>'
+'<li><a>Использованиек побочного эффекта вызванного модуля</a><br>'
+'<i>Запускается сам модуль, но никакая информация из него не импортируется(нужен'
+' только эффект)</i><br>Простешая версия<br>'
+'import myDefault from "/modules/my-module.js";</li>'
+'<li><a>Импорт значения по умолчанию</a><br><i>создаём дефолтный export&ensp;(понял, ради импорта)</i><br>'
+'-import myDefault from "/modules/my-module.js";<br><i>импортировать можно всё:</i><br>'
+'-import myDefault, * as myModule from "/modules/my-module.js";<br>'
+'<i>! myModule тут объявлена в качестве пространства имён</i> "или"<br>'
+'-import myDefault, {foo, bar} from "/modules/my-module.js";<br>'
+'<i>! конкретные значения поимённо</i></li>'
+'<li><a>Импорт переменных</a><br><ul><i>следующий код вызовет ошибку '
+'(смотри какой)</i>'
+'<li type="square">my-modules.js<br><i>export let <b>a = 2;</b><br>'
+'export let <b>b = 3;</b></i></li>'
+'<li type="square">main.js<br><i>import { a, b } from "/modules/my-module.js"<br>'
+'<a>a = 5;<br>b = 6;</a></i><br>'
+'Unsigned TypeError: Assignment to constant variable</i></li></ul><ul>'
+'<i>А такой будет рабочим:</i><br>'
+'<li type="disc"><a>my-modules.js:</a><br>'
+'export let <a>obj = { a: 2, b: 4 };</a></li>'
+'<li type="disc"><a>main.js:</a><br>'
+'import { obj } from "/modules/module.js";<br><a>obj.a = 1;<br>obj.b = 4;</a></li>'
+'</ul></li>'
+'<li><a>Динамический импорт</a><br>'
+'<i>тут вызов import() возвращает Promice.</i><br>'
+'import ("/modules/my-module.js").then ((module) => {<br>'
+'<i>//издеваемся над модулем</i><br>});<br>'
+'<i>await тоже пойдёт</i><br>'
+'let module=await import("/modules/my-module.js");</li>'
+'<ul><a>Пишем примеры</a> (импорт из впомогательного модуля. Если не поленился и написал)<br>'
+'<li type="disc"><h5>Модуль: file.js</h5><br>'
+'<i>Следующие модули пишем в отдельных файлах и подключаем их к бозовому (лень заморачиваться, '
+'поэтому просто обозначу)</i><br>'
+'function getJSON(url, callback){<br>'
	+'let xhr=new XMLHHttpRequest();<br>'
	+'xhr.onload=function(){<br>'
		+'callback(this.responseText);<br>'
	+'};<br>'
	+'xhr.open("GET",url,true);<br>'
	+'xhr.send();}<br>'
+'export function getUsefulContents(url,callback){<br>'
	+'getJSON(url,(data)=>callback(JSON.parse(date))))<br>}<br>'
+'</li>'
+'<li type="disc"><h5>Основной код: main.js</h5>'
+'import { getUsefulContents } from "/modules/file.js";<br>'
+'getUsefulContents("http://www.example.com", (data) => {<br>'
	+'doSomethingUseful(data);<br>'
+'});<br></li>'
+'<li type="square"><h5>Динамический импорт</h5>'
+'<i>Загрузка модуля в зависимости от действий пользователя (тут import() используется '
+'совместно c await)</i><br>'
+'const main=document.querySelector("main");<br>'
+'for(const link of document.querySelectorAll("nav > a")){<br>'
+'	link.addEventListener("click",(e) => {<br>'
	+'	e.preventDefault();<br>'
+'		import("/modules/my_module.js")<br>'
		+'.then((module) => {<br>'
	+'		module.loadPageInfo(main);<br>'
+'		})<br>'
		+'.catch((err) => {<br>'
	+'		main.textContent=err.message;<br>'
+'}); }); }<br>'
+'</li><a>Как всем этим пользоваться, я не разбирался. Но код правильный - страницы загружаются</a><br>'
+'<hr><li><a>outherHTML: HTML элемента целиком</a><br>'
+'&ensp;Пример:<br>'
+'&lt;div id "elem">Hello <a style="margin:0">world</a></div> //<i>то же самое делает следующее:</i><br>'
+'&lt;script>alert(elem.outerHTML); <i>зачем надо - не понял</i><br>'
+'&lt;/script><br>'
+'outerHTML вообще элемент не изменяет. Он заменяется полностью во внешнем контесте<br>'
+'<div>привет, мир!</div><br>'
+'let div=document.querySelector("div");<br>'
  +' div.outerHTML="&lt;p>New Element&lt;/p>"; <br>'
+'   alert(div.outerHTML); <i>//<div>привет, мир! Ну, и там разметка...</div></i><br>'
+'<div> - постоянно один и тот-же и  вместе outerHTML остаётся тем-же значением<br>'
+'<i>Был вставлен новый элемент, но не сохранён в переменной.</i><br>'
+'<i>произошло следующее:</i><br>'
+'<li type="square">div был удалён из документа</li>'
+'<li type="square">Вместо него был вставлен другой элемент HTML &lt;p>что-то там&lt;p/></li>'
+'<li type="square">а в div осталось старое значение. HTML - то мы не стали сохранять</li>'
+'<i>Что-то подобное используется при innerHTML, при outerHTML ничего не случится.</i><br></li><li>'
+'<a style="color:blue">nodeValue/data: содержимое текстового узла</a><br></li><li>'
+'<i>Использование innerHTML для создания элементов логирования на страницу</i><br>'
+'<a>HTML</a><br>'
+'&lt;div class="box"><br>'
  +' &lt;div>&lt;strong>log:&lt;/strong>&lt;div><br>'
  +' &lt;div class="log">&lt;/div><br>'
+'&lt;/div> <br>'
+'<a>JS</a><br>'
+'"use strict"<br>'
+'function log(msg){<br>'
	+'var logElem=document.querySelector(".log");<br>'
+'	var time=new Date();<br>'
	+'var timeStr=time.toLocaleTimeString();<br>'
	+'logElem.innerHTML += timeStr + ": " + msg + "<br/>";<br>'
+'}log("Регистрация событий мыши внутри этого контейнера...");<br>'
+'<i>//что-то регистрирует(что - не понял)</i><br>'
+'function logEvent(event) {<br>'
 +' var msg =<br>'
    +'"Event <strong>" +<br>'
    +'event.type +<br>'
    +'"</strong> at <em>" +<br>'
    +'event.clientX +<br>'
    +'", " +<br>'
    +'event.clientY +<br>'
    +'"</em>";<br>'
  +'log(msg);}<br>'
+'var boxElem = document.querySelector(".box");<br>'
+'boxElem.addEventListener("mousedown", logEvent);<br>'
+'boxElem.addEventListener("mouseup", logEvent);<br>'
+'boxElem.addEventListener("click", logEvent);<br>'
+'boxElem.addEventListener("mouseenter", logEvent);<br>'
+'boxElem.addEventListener("mouseleave", logEvent);<br>'
+'<i>//Понял. Регистрирует движение мыши и отмечает клики по времени</i>'
+'<a><h5 style="margin-top:5px">log:</h5><br>'
+'09:11:32: Регистрация событий мыши внутри этого контейнера...<br>'
+'09:11:43: Event mouseenter at 118, 522<br>'
+'09:11:43: Event mouseleave at 40, 621<br>'
+'09:11:49: Event mouseenter at 51, 548<br>'
+'09:11:49: Event mouseleave at 49, 554<br>'
+'09:12:02: Event mouseenter at 50, 417<br>'
+'09:12:03: Event mouseleave at 49, 401<br>'
+'09:12:08: Event mouseenter at 51, 330<br>'
+'09:12:09: Event mousedown at 52, 330<br>'
+'09:12:12: Event mouseup at 461, 608<br>'
+'09:12:12: Event click at 461, 608<br></a>'
+'<i>Регистрирует события, сделанные мышкой. Животное...</i></li><li>'
+'<a>textContent: просто текст</a><br>'
+'&lt;div id "news"><br>'
  +' &lt;h3>Warning!</h3><br>'
 +'  &lt;p>Mars attack!&lt;/p><br>'
+'&lt;/div><br>'
+'&lt;script><br>'
  +' <i>//scnelle</i><br>'
  +' alert(news.textContent);<br>'
   +'&lt;/script> <i>//Warning!Mars attack! (только текст)</i><br>'
+'<ul><a>Пробуем TextContent</a><br>'
+'<li type="disc">C innerHTML втавка происходит, как обычная css-разметка</li>'
+'<li type="disc">C textContent вставка получается как текст, где символы трактуются '
+'буквально</li></ul>'
+'&lt;div id "elem1">&lt;/div><br>'
+'&lt;div id "elem2">&lt;/div><br>'
+'&lt;script><br>'
  +' let name=prompt("Enter name ","&lt;b>Viny!&lt;/b>");<br>'
+'   elem1.innerHTML=name; <i>//Enter name (без кавычек)</i><br>'
  +' elem2.textContent=name; <i>//"&lt;b>Viny&lt;/b>" (теги, кавычки - все дела)</i><br>'
+'&lt;/script><br>'
+'</li></ul>'
+'</ol>'

+'</td><td id="pravcool">'
+'<li><i>Предложение ввести два числа и последующее вычисленнее их суммы</i><br>'
+'let i,j,sum;<br>'
+'i=prompt("givo 2 cifry: "," ");<br>'
+'j=prompt("vtoraya"," ");<br>'
+'sum=+i+(+j);<br>'
+'alert(sum);</li>'
+'<ul><h5>Метка</h5>'
+'<i>Используются с операторами break и continue</i><br>'
+'<li type="square"><a>Пример интерактивный</a><br>'
+'let str="";<br>'
+'let s=prompt("final",""); <i>//5</i><br>'
+'loop1: for (let i = 0; i < s; i++){<br>'
	+'if (i === 3){  <i>//!</i><br>'
		+'continue loop1; <i>//!</i><br>'
	+'}<br>'
	+'str=str+i;<br>'
+'}<br>'
+'	alert(str); <i>//0124</i><br>'
+'</li>'
+'<li type="square"><a>Использование метки с оператором break в цикле</a><br>'
+'let i,j;<br>'
+'loop1: for (i = 0; i < 3; i++){ <i>//это первый цикл с меткой</i><br>'
  +' loop2: for (j = 0; j < 3; j++){ <i>//второй цикл</i><br>'
+'      if(i===1 && j ===1){<br>'
		+'  continue loop1;<br>'
	+'  }alert("i= " + i + ", j= "+ j);<br>'
+'}} <i>/*i= 0, j= 0<br>'
	  +'i= 0, j= 1<br>'
	+'  i= 0, j= 2<br>'
+'	  i= 1, j= 0<br>'
	  +'i= 2, j= 0<br>'
	+'  i= 2, j= 1<br>'
+'	  i= 2, j= 2*/</i><br></li>'
+'<li type="square"><a>Ещё одна примера:</a><i>(вычиляем число правильных ответов '
+'при тесте)</i><br></li><li style="background:yellow">'
+'Ещё пример использолвания метки с break<br>'
+'<i style="color:green, backgrond-color:maroon">Смотрим все-ли элементы проходят все тесты</i><br>'
+'let allPass = true;<br>'
+'let i, j;<br>'
+'top: for (i = 0; i < items.length; i++) {<br>'
  +'for (j = 0; j < tests.length; j++) {<br>'
    +'if (!tests[j].pass(items[i])) {<br>'
      +'allPass = false;<br>'
      +'break top;}}<br>'
+'} <i>//вааще не понял, что к чему</i></li><br>'
+'<li type="square">'
+'</li>'
+'<li type="square"></li>'
+'</ul>'
+'<ul><h4>Document</h4>'
+'<li style="background:#a5a"><a>document.getElementById</a><br>'
+'&lt;div id="shilo">&lt;div id "shilo-content">Остриё!&lt;/div>&lt;/div><br>'
+'&lt;script>let shilo=<i>document.getElementById("shilo")</i>;<br>'
+'shilo.style.background="green";<br>&lt;/script>'
+'<div id="shilo"><div id "shilo-content">Остриё!</div></div><br>'
+'<nobr><i>//Остриё на зелёном фоне</i></li><li>'
+'&lt;div id="param">Golodno&lt;/div><br>'
+'&lt;script><br>'
+'param.style.background="#a05acf"; <i>//на сиреневом фоне Golodno</i><br>'
+'&lt;/script><br>' 
+'</li></ul><ul><h3>Свойства узлов: тип, тег и содержимое</h3>'
+'<li><a>Классы DOM-узлов</a><br>'
+'&lt;a>, &lt;input> и др. - узлы, могут иметь разные свойства<br>'
+'<a>Основные классы<br>'
+'<img src="https://i.postimg.cc/47pDTkDG/DOM.png" width="500"></a>'
+'<ul><a>Есть классы следующих типов: </a><br>'
+'<li type="disc"><b>EventTarget</b> - корневой класс абсолютно для всего.<br> Благодаря ему все '
+'DOM-узлы подерживают любые "события"<br>'
+'<ul><i>К ним относятся следующие типы:</i><br>'
+'<li type="square">type(string)</li>'
+'<li type="square">callback(null)</li>'
+'<li type="square">capture(bool, false)</li>'
+'<li type="square">passive(null)</li>'
+'<li type="square">once(bool, false)</li>'
+'<li type="square">signal(null)</li>'
+'<li type="square">removed(bool, false)</li></ul>'
+'</li>'
+'<li type="disc"><b>Node</b> - абстрактный класс, основа DOM - узлов</li>'
+'<li type="square"><a>Document </a> служит точкой входа в DOM.<br> HTMLDocument - это он</li>'
+'<li type="square"><a>CharacterData </a>- абстрактный класс. Наследуется:'
+'<ul><li type="disc">Text - текст внутри элемента</li>'
+'<li type="disc">Comment - комментарии. Не отображается,<br> но становится членом DOM</li></ul><br></li>'
+'<li type="disc"><b>Element </b>- базовый класс для DOM-элементов<br>'
+'навигация на уровне  элементов: nextElementSibling, children<br> и методы поиска: '
+'getElementByTagName, querySelector.</li>'
+'<li type="disc"><b>HTMLElement</b> является базовым классом<br> для всего'
+' остального HTML.<ul><i>От него наследуются:</i>'
+'<li type="disc"><a>HTMLInputElement </a>- класс для тега &lt;input></li>'
+'<li type="disc"><a>HTMLBodyElement </a>- класс для тега 0&lt;body></li>'
+'<li type="disc"><a>HTMLAnchorElement </a>- класс для тега &lt;a></li>'
+'<li type="disc">...и далее по списку.</li>'
+'</ul></li><ul></li><li>'
+'<a>Рассмотрим DOM-объект для<br> тега &lt;input><input></a><br>'
+'<ul><i>получние свойств и методов в порядке наследования:</i>'
+'<br><li type="disc">HTMLInputElement - этот класс<br> предоставляет специфичные '
+'для элементов формы свойства,</li>'
+'<li type="disc">HtmlElement - предоставляет общие для<br> HTML-элементов '
+'методы (и геттеры/сеттеры),</li>'
+'<li type="disc">Element - предоставляет типовые методы элемента,</li>'
+'<li type="disc">Node - предоставляет общие свойства DOM-узлов,</li>'
+'<li type="disc">EventTarget - обеспечивает поддержку событий,</li>'
+'<li type="disc">кроме того, наследует от Object, поэтому<br> доступны методы '
+'"обычного объекта"</li></ul>'
+'<i>Узнаем имя класса DOM-узла:</i><br>'
+'alert(document.body.constructor.name); <i>//HTMLBodyElement</i><br>'
+'<i>Или приведём к строке:</i><br>'
+'alert(document.body); <i>//[object HTMLBodyElement]</i><br>'
+'<a>instanceof</a> тоже может указать на наследование:<br>'
+'alert(document.body instanceof EventTarget || Node || Element |<br>'
+'|HTMLElement || HTMLBodyElement); <i>//true везде</i><br></li><li>'
+'<b>Свойство "nodeType"</b> <i>способ узнать тип DOM-узла</i><br>'
+'<i>Значением является цифра:</i><br>'
+'<li type="square">elem.node Type == 1 для узлов элементов,</li>'
+'<li type="square">elem.node Type == 3 для текстовых узлов,</li>'
+'<li type="square">elem.node Type == 9 для объектов документа</li>'
+'<li type="square">остальные значения в'
+'<a style="margin-left:5pt" href="https://dom.spec.whatwg.org/#node">спецификации</a></li>'
+'<i>Посмотрим пример:</i><br>'
+'let elem=document.body;<br>'
+'<i>//смотрим тип</i><br>'
+'alert(elem.nodeType); <i>//1 (ага, узел-элемент)</i><br>'
+'<i>//вычисляем первого потомка...</i><br>'
+'alert(elem.firstChild.nodeType); <i>//1 (узел-элемент)</i><br>'
+'<i>//значение типа для document</i><br>'
+'alert(document.nodeType); <i>//9 (значение типа document)</i><br></li><hr><li>'
+'<a>Тег: nodeName и tagName</a><br>'
+'alert( document.body.nodeName); <i>//BODY (большими буквами)</i><br>'
+'alert(document.body.TagName); <i>//undefined (не увидел. Его навреное и<br> нет. '
+'Он только для элементов Element. Тоже пойдёт)</i><br>'
+'<ul><i style="color:#05f">Есть разница, но для многих она неочевидна:</i><br>'
+'<li type="disc">Свойство tagName есть только у элементов Element.</li>'
+'<li type="disc">Свойство nodeName определено для луюбых узлов Node;</li>'
+'<li style="color:green">&ensp;для элементов оно равно tagName</li>'
+'<li style="color:blue">&ensp;для остальных типов узлов оно содержит строку с типом узла.</li></ul>'
+'<a>Сравнение tagName и nodeName</a><br>'
+'<i>//для комментария:</i><br>'
+'alert( document.body.firstChild.tagName); <i>//H3 (элемент)</i><br>'
+'alert( document.body.firstChild.nodeName); <i>//H3 (тоже определил)</i><br>'
+'<i>// for document</i><br>'
+'alert( document.tagName); <i>//undefined (не является элементом)</i><br>'
+'alert( document.nodeName); <i>//#document (так и сказал)</i><br></li><li>'
+'<a>innerHTML: </a>содержимое элемента<br>'
+'alert( document.body.innerHTML); <i>//идёт чтение body</i><br>'
+'document.body.innerHTML="newTusha!"; <i>//изменился заголовок <br>'
+'страницы на newTusha</i><br>'
+'document.body.innerHTML="&lt;b><style="margin-left:5px">test"; <br><i>'
+'//сделали ошибку(не поставили &lt;/b>) и теперь все буквы строчные</i><br>'
+'alert(document.body.innerHTML); //<i style="margin:0">'
+'<b style="margin:5pt">test</b> (ошибка исправлена самой программой)</i><br>'
+'<table border="1" style="border-color:#777"><td><a>Скрипты не выполняются</a><br>Если innerHTML вставляет в документ '
+'тег &lt;script> - он<br> становитсяч частью HTML, но не запускается</td></table></li><li>'
+'<a><center>Ща покажем, как "innerHTML+=" осуществляет<br> перезапись:</center/a><br>'
+'<a style="margin-left:1cm"><img src="https://i.postimg.cc/hJXsxw6G/perep.png">&ensp;И с чьей помощью</a><br>'
+'chatDiv.innerHTML += "<div>Привет!<img src="https://i.postimg.cc/7hR8jXd1/ihtml.jpg"></div>";'
+'chatDiv.innerHTML += "Как дела?";<br>'
+'</li></ul>'
+'</td></table>'

let domu;
domu='<table><td id="levcool">'
+'<ul><h5>Продолжим</h5><br><li>'
+'<a>Свойство "hidden" рассмотрим</a><br>'
+'&lt;div>Ничего не должно быть видно&lt;/div> (<i style="margin-left:0">эта строка выведена</i>)<br>'
+'&lt;div hidden>Атрибут hidden&lt;/div> <i>//не видать ничего</i><br>'
+'&lt;div id="elem">Назначим JS свойство "hidden"&lt;/div><br>'
+'elem.hidden=true; <i>//это уже скрипт (Атрибут hidden), видно всё</i><br><br>'
+'&lt;div id="elem">Mig - 21&lt;/div> <i>//появляется и исчезает каждую секунду</i><br>'
+'setInterval(()=>elem.hidden=!elem.hidden,1000);<br></li><li>'
+'<a>Другие свойства</a><br>'
+'<ul><i>Для примера:</i><br>'
+'<li type="disc"><a>value - </a>значение для &lt;input>,&lt;select>,&lt;textarea>'
+'(HTMLInputElement, HTMLSelectElement...).</li>'
+'<li type="disc"><a>href - </a>адрес ссылки "href" для <a href="...">'
+'(HTMLAnchorElement).</li>'
+'<li type="disc"><a>id - </a>значение атрибута "id" для всех элементов'
+'(HTMLElement).</li>'
+'<li type="disc"><a>...</a>другие<a>...</a></li></ul>'
+'<i>Приведём пример:</i><br>'
+'&lt;<i>input</i> type "text" id "elem" value "значение">'
+'<input type "text" id "elem" value "значение">'
+'alert(elem.type); <i>//окошко для ввода</i><br>'
+'alert(elem.id); <i>//вообще не понятно, зачем</i><br>'
+'alert(elem.value); <i>//значение какое-то(там код в отдельном окошке)</i><br>'
+'<ul><a>Итог:</a><br>'
+'<li><a style="color:green">nodeType</a> - тип DOM-узла(1,3...)</li>'
+'<li><a style="color:green">nodeName/tagName</a> - возвращает название тега.'
+'Только чтение. Для неэлементов - делает краткую опись</li>'
+'<li><a style="color:yellow">innerHTML</a> - HTML - содержимое, которое можно менять</li>'
+'<li><a style="color:blue">outherHTML</a> - полный HTML узла-элемента</li>'
+'<li><a style="color:#484">nodeValue/data</a> - неэлемент (текст, комментарий)</li>'
+'<li><a style="color:#844">textContent</a> - всё, включая теги, идёт текстом</li>'
+'<li><a style="color:№448">hidden</a> - делает то же самое, что и dysplay:none(CSS)</li></ul><ul>'
+'<b>!</b><a> Задачи</a><br>'
+'<li type="disc 3"><br>'
+'<ul style="font-color:red"><br>'
+'   <li style="color:red">Животные'
      +'<ul>'
	+'    <li style="color:blue">&ensp;Млекопитающие</li>'
+'	     <li style="color:#480">Коровы</li>'
	     +'<li style="color:#880">Ослы</li>'
	   +'  <li>Собаки</li>'
     +' </ul></li>'
   +'<li>&ensp;Другие'
 +'     <ul><li  style="color:maroon">Змеи</li>'
	  +'   <li>Птицы</li>'
	+'     <li>Ящерицы</li>'
  +'    </ul></li></ul></li>'
+'<li  style="color:#afa">&ensp;Рыбы'
+'   <ul><li>Аквариумные<ul>'
		  +'  <li>Гуппи</li>'
		+'    <li>Рыба-ангел</li>'
	  +'   </ul></li><li>&ensp;Морские'
	+'     <ul><li>Морская форель</li>'
+'	     </ul></li></ul></li></ul>'
+'<b>JS - код:</b><br>'
+'for(let li of document.querySelectorAll("li")){<br>'
	+'<i>//получаем название из текстового узла</i><br>'
+'	let title=li.firstChild.data;<br>'
	+'title=title.trim(); <i>//удвляем лишние пробелы с конца строки<br>'
+'	//считываем количество потомков</i><br>'
	+'let count=li.getElementsByTagName("li").length;<br>'
+'	alert(title + ": " + count);}<br></li><li>'
+'<a>Что содержит свойство nodeType?</a><br>'
+'alert(document.body.lastChild.nodeType); <i>//1 (узел элемент)<br>'
+'браузер тормоз считает, что &lt;script> является последним элементом </i><br></li><li>'
+'<a>Тег в комментарии</a><br>'
+'let body = document.body;<br>'
+'body.innerHTML="<!--" + body.tagName + "-->";<br>'
+'alert(body.firstChild.data); <i>//DODY</i><br></li><li>'
+'<a>И, где в DOM-иерархии "document"?</a><br>'
+'&ensp;<b>Так:</b><br> alert(document); <i>//[object HTMLDocument]</i><br>'
+'&ensp;<b>Можно так:</b><br> alert(document.constructor.name); <i>//HTMLDocument</i><br>'
+'<i>Используем prototype и увидим ссылку на функцию-конструктор</i><br>'
+'alert(HTMLDocument.prototype.constructor === HTMLDocument); <i>//true</i><br>'
+'<i>Проуйдёмся по всей цепочке прототипов document:</i><br>'
+'alert(HTMLDocument.prototype.constructor.name); <i>//HTMLDocument</i><br>'
+'alert(HTMLDocument.prototype.__proto__.constructor.name); <i>//Document</i><br>'
+'alert(HTMLDocument.prototype.__proto__.__proto__.constructor.name); <i>//node</i><br>'
+'можно использовать<br>'
+'console.dir(document); <i>//nodeName: "#document",nodeType: 9. И много всего, мне ненужного</i><br>'
+'</li>'
+'</ul>'
+'</td><td id="pravcool">'
+'<ul><h4>Атрибуты и свойства</h4>'
+'Для примера: тег &lt;body id="page">, а у DOM-объекта будет свойство для него - '
+'body.id="page"<br><li>'
+'<a>DOM-свойства</a><br>'
+'document.body.myData={<br>'
	+'name:"Cesar",<br>'
	+'title: "Imperator"<br>'
+'}; alert(document.body.myData); <i>//[object Object]</i><br>'
+'alert(document.body.myData.name); <i>//Cesar</i><br>'
+'alert(document.body.myData.title); <i>//Imperator</i><br>'
+'<i>Указываем метод:</i><br>'
+'document.body.sayTagName=function(){<br>'
+'alert ( this.tagName );<br>'
+'}; <br>'
+'document.body.sayTagName(); <i>//BODY</i><br>'
+'document.body.sayTagName(this); <i>//тоже BODY</i><br>'
+'<i>Изменяем встроенные прототипы и добовляем новые методы:</i><br>'
+'Element.prototype.sayHi=function(){<br>'
	+'alert(`Hello, I&lsquo;m ${this.tagName}`);<br>'
+'};<br>'
+'document.documentElement.sayHi(); <i>//Hello, I&lsquo;m HTML</i><br>'
+'document.body.sayHi(); <i>// Hello, I&lsquo;m BODY</i><br></li><li>'
+'<a>HTML - атрибут</a><br>'
+'&lt;body id="test" something="non-standard"><br>'
+'&lt;script><br>'
+'alert(document.body.id); <i>//test</i><br>'
+'<i>//нестандартный атрибут в свойство не преобразуется</i><br>'
+'alert(document.body.something); <i>//undefined</i><br>'
+'&lt;/script/body><br>'
+'<i>//А, смачный пример</i></i><br>'
+'</li></ul>'
+'</td></table>'

document.write(domu); //ifel prod
 